HEAD http://example.com/api/users HTTP/1.1
HTTP/1.1 404 Not Found
date: Tue, 12 May 2026 12:47:47 GMT
content-type: text/html
connection: keep-alive
server: cloudflare
age: 318
cf-cache-status: HIT
cf-ray: 9fa988b318515230-MXP

